#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Blog: https://helmiau.com
# HelmiWrt by helmiau.com
#=================================================

name: Build OpenJDK for OpenWrt

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Select OpenJDK version option (check http://dl-cdn.alpinelinux.org/alpine for newer version)
        required: true
        default: 3.17
      build_option:
        type: choice
        description: Select OpenJDK build option
        required: true
        default: all
        options: 
        - all
        - jdk8
        - jdk9
        - jdk10
        - jdk11
        - jdk12
        - jdk13
        - jdk15
        - jdk16
        - jdk17

env:
  TZ: Asia/Jakarta
  THIS_REPO_NAME: ${{ github.event.repository.name }}
  THIS_REPO_BRANCH: ${{ github.event.repository.default_branch }}
  REPO_BRANCH: ${{ github.event.inputs.build_option }}

jobs:
  Build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo "FILE_DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
          export JDK_VER="$(echo '${{ github.event.inputs.release_version }}')"
          echo "JDK_VER=$JDK_VER" >> $GITHUB_ENV
          export JDK_OPT="$(echo '${{ github.event.inputs.build_option }}')"
          echo "JDK_OPT=$JDK_OPT" >> $GITHUB_ENV

      - name: Setting Permissions
        id: sett_perm
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x $GITHUB_WORKSPACE/gitbuild/*.sh
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Building Packages
        id: build_pkgs
        if: steps.sett_perm.outputs.status == 'success' && !cancelled()
        run: |
          cd $GITHUB_WORKSPACE
          if [[ $JDK_OPT == "all" ]]; then
            JDK1S="jdk8 jdk9 jdk10 jdk11 jdk12 jdk13 jdk14 jdk15 jdk16 jdk17"
            for jdkxv in $JDK1S;do
                echo "Building $jdkxv..."
                $GITHUB_WORKSPACE/gitbuild/build-jdk.sh $JDK_VER $jdkxv
            done
          else
            echo "Building $JDK_OPT..."
            $GITHUB_WORKSPACE/gitbuild/build-jdk.sh $JDK_VER $JDK_OPT
          fi
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Listing Files
        id: listing_files
        if: steps.build_pkgs.outputs.status == 'success' && !cancelled()
        run: |
          cd $GITHUB_WORKSPACE
          [ ! -d uploadPath ] && mkdir uploadPath
          export UPLOADPATH="$GITHUB_WORKSPACE/uploadPath"
          echo "UPLOADPATH=$UPLOADPATH" >> $GITHUB_ENV
          find . -type f -name 'openjdk*' | while read FILE ; do
            echo -e "helmilog:: File located at $(readlink -f ${FILE})"
            mv $(readlink -f ${FILE}) "${UPLOADPATH}/${FILE}"
          done
          echo "Rechecking files..."
          find . -type f -name 'openjdk*' | while read FILE ; do
            echo -e "helmilog:: File located at $(readlink -f ${FILE})"
          done
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Generate New Release Tag
        id: tag
        if: steps.listing_files.outputs.status == 'success' && !cancelled()
        run: |
          sleep 5
          echo "release_tag=openjdk-build-v$JDK_VER" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload Files to Github Release
        uses: ncipollo/release-action@v1.12.0
        if: steps.tag.outputs.status == 'success' && !cancelled()
        with:
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          name: OpenJDK v${{ env.JDK_VER }} ${{ env.FILE_DATE }}
          tag: ${{ steps.tag.outputs.release_tag }}
          commit: ${{ env.CURRENT_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.UPLOADPATH }}/*
          body: |
            **OpenJDK Build for OpenWrt**
            [Donation here](https://www.helmiau.com/pay) • [Installation Tutorial](https://www.google.com/search?q=helmiau.com+helmiwrt+packages)
